---
title: CutefishOS
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: CutefishOS
description: Cutefish Built on Ubuntu
avatar: https://raw.githubusercontent.com/cutefish-ubuntu/cutefish-ubuntu.github.io/master/images/cutefish-logo.png
footer-links:
  dribbble: 
  email: cutefish.ubuntu@gmail.com
  facebook: 
  flickr: 
  github: cutefish-ubuntu
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
disqus: cutefish-ubuntu
google_analytics: G-PXWBYKLNGL
url: https://cutefish-ubuntu.github.io/
baseurl: 
markdown: redcarpet
highlighter: pygments
permalink: "/:title/"
version: v1.0.0
sass:
  style: expanded
gems:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
