---
title: CutefishOS
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: CutefishOS
email: your-email@example.com
description: CutefishOS Built on Ubuntu
avatar: https://raw.githubusercontent.com/cutefish-ubuntu/cutefish-ubuntu.github.io/master/images/cutefish-logo.png
baseurl: 
url: https://cutefish-ubuntu.github.io/
twitter_username: 
github_username: 
markdown: kramdown
highlighter: pygments
permalink: "/:title/"
remote_theme: jekyll-now
plugins:
- jekyll-feed
sass:
  style: expanded
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
